project_id = "kubhguqlihooofnyvdpq"

[functions.chat]
verify_jwt = false

[functions.generate-room-design]
verify_jwt = false

[functions.send-confirmation-email]
verify_jwt = false

[functions.send-broadcast-email]
verify_jwt = false

[functions.delete-user]
verify_jwt = false

[functions.record-broker-agreement]
verify_jwt = false

[functions.get-maps-config]
verify_jwt = false

[functions.get-commute-time]
verify_jwt = false
