// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { defineMcp } from "npm:@lovable.dev/mcp-js@0.20.0";

// src/lib/mcp/tools/search_properties.ts
import { createClient } from "npm:@supabase/supabase-js@^2.56.0";
import { defineTool } from "npm:@lovable.dev/mcp-js@0.20.0";
import { z } from "npm:zod@^3.25.76";
function sb() {
  return createClient(
    process.env.SUPABASE_URL,
    process.env.SUPABASE_PUBLISHABLE_KEY ?? process.env.SUPABASE_ANON_KEY,
    { auth: { persistSession: false, autoRefreshToken: false } }
  );
}
var search_properties_default = defineTool({
  name: "search_properties",
  title: "Search properties",
  description: "Search Rumi property listings by city, listing type (sale/rent), property type, price range, and bedrooms. Returns a compact list.",
  inputSchema: {
    city: z.string().optional().describe("City or municipality name filter (case-insensitive contains)."),
    listing_type: z.enum(["sale", "rent"]).optional().describe("Filter by sale or rent."),
    property_type: z.string().optional().describe("Filter by property type (e.g. apartment, villa)."),
    min_price: z.number().optional(),
    max_price: z.number().optional(),
    min_bedrooms: z.number().int().optional(),
    limit: z.number().int().min(1).max(50).optional().describe("Max results (default 20).")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ city, listing_type, property_type, min_price, max_price, min_bedrooms, limit }) => {
    let q = sb().from("properties_public").select(
      "id, address, city, municipality, property_type, listing_type, bedrooms, bathrooms, square_meters, price, rental_price, status"
    ).eq("status", "active").limit(limit ?? 20);
    if (city) q = q.or(`city.ilike.%${city}%,municipality.ilike.%${city}%`);
    if (listing_type) q = q.eq("listing_type", listing_type);
    if (property_type) q = q.eq("property_type", property_type);
    if (min_bedrooms != null) q = q.gte("bedrooms", min_bedrooms);
    if (listing_type === "rent") {
      if (min_price != null) q = q.gte("rental_price", min_price);
      if (max_price != null) q = q.lte("rental_price", max_price);
    } else {
      if (min_price != null) q = q.gte("price", min_price);
      if (max_price != null) q = q.lte("price", max_price);
    }
    const { data, error } = await q;
    if (error) {
      return { content: [{ type: "text", text: `Error: ${error.message}` }], isError: true };
    }
    return {
      content: [{ type: "text", text: JSON.stringify(data ?? [], null, 2) }],
      structuredContent: { results: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/get_property.ts
import { createClient as createClient2 } from "npm:@supabase/supabase-js@^2.56.0";
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@0.20.0";
import { z as z2 } from "npm:zod@^3.25.76";
function sb2() {
  return createClient2(
    process.env.SUPABASE_URL,
    process.env.SUPABASE_PUBLISHABLE_KEY ?? process.env.SUPABASE_ANON_KEY,
    { auth: { persistSession: false, autoRefreshToken: false } }
  );
}
var get_property_default = defineTool2({
  name: "get_property",
  title: "Get property details",
  description: "Fetch full public details for a single Rumi property by its UUID.",
  inputSchema: {
    id: z2.string().uuid().describe("Property UUID.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ id }) => {
    const { data, error } = await sb2().from("properties_public").select("*").eq("id", id).maybeSingle();
    if (error) {
      return { content: [{ type: "text", text: `Error: ${error.message}` }], isError: true };
    }
    if (!data) {
      return { content: [{ type: "text", text: "Property not found" }], isError: true };
    }
    return {
      content: [{ type: "text", text: JSON.stringify(data, null, 2) }],
      structuredContent: { property: data }
    };
  }
});

// src/lib/mcp/tools/list_agencies.ts
import { createClient as createClient3 } from "npm:@supabase/supabase-js@^2.56.0";
import { defineTool as defineTool3 } from "npm:@lovable.dev/mcp-js@0.20.0";
import { z as z3 } from "npm:zod@^3.25.76";
function sb3() {
  return createClient3(
    process.env.SUPABASE_URL,
    process.env.SUPABASE_PUBLISHABLE_KEY ?? process.env.SUPABASE_ANON_KEY,
    { auth: { persistSession: false, autoRefreshToken: false } }
  );
}
var list_agencies_default = defineTool3({
  name: "list_agencies",
  title: "List agencies",
  description: "List real estate agencies on Rumi, optionally filtered by name.",
  inputSchema: {
    name: z3.string().optional().describe("Case-insensitive name filter."),
    limit: z3.number().int().min(1).max(100).optional()
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ name, limit }) => {
    let q = sb3().from("agencies").select("id, name").limit(limit ?? 50);
    if (name) q = q.ilike("name", `%${name}%`);
    const { data, error } = await q;
    if (error) {
      return { content: [{ type: "text", text: `Error: ${error.message}` }], isError: true };
    }
    return {
      content: [{ type: "text", text: JSON.stringify(data ?? [], null, 2) }],
      structuredContent: { agencies: data ?? [] }
    };
  }
});

// src/lib/mcp/index.ts
var mcp_default = defineMcp({
  name: "rumi-mcp",
  title: "Rumi Real Estate",
  version: "0.1.0",
  instructions: "Tools for browsing Rumi real estate listings. Use `search_properties` to filter listings by city, price, and type, `get_property` to fetch full details for a listing UUID, and `list_agencies` to look up agencies.",
  tools: [search_properties_default, get_property_default, list_agencies_default]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.20.0/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
