// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://kubhguqlihooofnyvdpq.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imt1YmhndXFsaWhvb29mbnl2ZHBxIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTU4Njc4OTEsImV4cCI6MjA3MTQ0Mzg5MX0.zyw6wp7I1WEhysAYuo1EYJiY8vxHx4iXcQdT-xPCnfo";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});